<?php

namespace Drivezy\LaravelUtility\Controllers;

use Drivezy\LaravelRecordManager\Controllers\RecordController;
use Drivezy\LaravelUtility\Models\UserPreference;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

/**
 * Class UserPreferenceController
 * @package Drivezy\LaravelUtility\Controllers
 */
class UserPreferenceController extends RecordController {
    /**
     * @var string
     */
    protected $model = UserPreference::class;

    /**
     * @param Request $request
     * @return mixed|null
     */
    public function store (Request $request) {
        $user = Auth::user();

        //check if the given user has the same preference or not.
        //if yes then update the same preference
        if ( $user ) {
            $record = UserPreference::where('user_id', $user->id)->where('key', $request->key)->first();
            if ( $record )
                return parent::update($request, $record->id);
        }

        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
