<?php

namespace Drivezy\LaravelUtility\Observers;


use Illuminate\Database\Eloquent\Model as Eloquent;
use Illuminate\Support\Facades\Auth;

/**
 * Class UserPreferenceObserver
 * @package Drivezy\LaravelUtility\Observers
 */
class UserPreferenceObserver extends BaseObserver {
    /**
     * @var array
     */
    protected $rules = [
        'key' => 'required',
    ];

    /**
     * @param Eloquent $model
     * @return bool
     */
    public function saving (Eloquent $model) {
        if ( Auth::check() )
            $model->user_id = $model->user_id ? : Auth::id();

        return parent::saving($model); // TODO: Change the autogenerated stub
    }

}
